; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;
;   Common Config

[env]
platform = espressif32
;platform = espressif32 @ 6.6.0
framework = espidf
extra_scripts = link_libs.py
lib_deps = cli
	printf

;   https://github.com/espressif/esp-protocols.git
;   https://github.com/espressif/esp-mqtt.git

build_flags = 
	-D USE_DEBUG=1
	-D ESP32
	-D FREERTOS=1
	-I lib
    -I third_party/opus/include
	-Wno-missing-field-initializers
    -D CLI_MAX_ARGS=20

;    -D CONFIG_IDF_TARGET_ESP32=1

upload_protocol = esptool
debug_tool = esp-prog
debug_port = localhost:3333
board_build.flash_mode = dio

[env:seeed_xiao_esp32c3]

board = seeed_xiao_esp32c3

board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
build_flags = ${env.build_flags} -D ESP32C3_XIAO -D ARCH_RISCV32
upload_port=/dev/ttyACM0

[env:c3_supermini]
board = lolin_c3_mini
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
build_flags = ${env.build_flags} -D ESP32C3_SUPERMINI -D ARCH_RISCV32
debug_init_break = break loop
debug_tool = cmsis-dap
upload_port=/dev/ttyACM0

#platform = espressif32@6.5.0

[env:esp32-s3-devkitc-1]

board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_flags = ${env.build_flags} -D ESP32_S3_DKC1 -D ARCH_XTENSA -D PO_I2C
debug_init_break = tbreak setup

upload_port=/dev/ttyUSB0
board.hwids = 0x303A,0x4001

;   FIN
