; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;
;   Common Config

[env]
platform = espressif32
;platform = espressif32 @ 6.6.0
framework = espidf
extra_scripts = pre:link_libs.py, scons_build.py
lib_deps = cli
	printf

;   https://github.com/espressif/esp-protocols.git
;   https://github.com/espressif/esp-mqtt.git

build_flags = 
	-D USE_DEBUG=1
	-D ESP32
	-D FREERTOS=1
	-I lib
    -I third_party/opus/include
	-Wno-missing-field-initializers
    '-Wformat=2'
    '-Werror=format'
    '-Wno-format-zero-length'
    '-Wno-format-nonliteral'
    -D CLI_MAX_ARGS=20
    -L third_party/build/
    -l libopus.a

;    -D CONFIG_IDF_TARGET_ESP32=1

upload_protocol = esptool
debug_tool = esp-prog
debug_port = localhost:3333
board_build.flash_mode = dio

[env:seeed_xiao_esp32c3]

board = seeed_xiao_esp32c3

board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
build_flags = ${env.build_flags} -D ESP32C3_XIAO -D ARCH_RISCV32
upload_port=/dev/ttyACM0

board_build.partitions = min_spiffs.csv

[env:c3_supermini]
board = lolin_c3_mini
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
build_flags = ${env.build_flags} -D ESP32C3_SUPERMINI -D ARCH_RISCV32
debug_init_break = break loop
debug_tool = cmsis-dap
upload_port=/dev/ttyACM0

board_build.partitions = min_spiffs.csv

[env:c6_supermini]

board = esp32-c6-devkitc-1
board_build.mcu = esp32c6
board_build.f_cpu = 160000000L
build_flags = ${env.build_flags} -D ESP32C6_SUPERMINI -D ARCH_RISCV32
upload_port=/dev/ttyACM0

board_build.partitions = min_spiffs.csv

[env:esp32-s3-devkitc-1]

board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_flags = ${env.build_flags} -D ESP32_S3_DKC1 -D ARCH_XTENSA -D PO_I2C
debug_init_break = tbreak setup

upload_port=/dev/ttyUSB0

; Force 2MB flash configuration
board_upload.flash_size = 2MB
board_upload.maximum_size = 2097152

board_build.partitions = min_spiffs.csv

[env:esp32-s3-devkitc-2]

board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_flags = ${env.build_flags} -D ESP32_S3_DKC2 -D ARCH_XTENSA -D PO_I2C
debug_init_break = tbreak setup

upload_port=/dev/ttyACM0

; Force 2MB flash configuration
board_upload.flash_size = 2MB
board_upload.maximum_size = 2097152

board_build.partitions = min_spiffs.csv

[env:esp32-dev]
board = esp32doit-devkit-v1
board_build.mcu = esp32
#board_build.f_cpu = 160000000L
build_flags = ${env.build_flags} -D ESP32_DEV -D ARCH_XTENSA
debug_init_break = break loop
debug_tool = cmsis-dap
upload_port=/dev/ttyUSB0

board_build.partitions = min_spiffs.csv

;
;

[env:esp32-lora]
board = ttgo-lora32-v21
board_build.mcu = esp32
board_build.f_cpu = 240000000L
build_flags = ${env.build_flags}
	-D ESP32_LORA
	-D ARCH_XTENSA
	-D CONFIG_CS_GPIO=18
	-D CONFIG_RST_GPIO=14
	-D CONFIG_MOSI_GPIO=27
	-D CONFIG_SCK_GPIO=5
	-D CONFIG_MISO_GPIO=19
    #-D LORA_RX

debug_tool = esp-prog
debug_init_break = tbreak setup
upload_port = /dev/ttyACM0

lib_deps = ${env.lib_deps} 
	git+https://github.com/Inteform/esp32-lora-library

board_build.partitions = min_spiffs.csv

;   FIN
